version: '3.7'
services:
  db:
    image: mongo:4.1
    volumes: 
      - ./data/mongodb/db:/data/db
      - ./data/mongodb/configdb:/data/configdb
    ports: 
      - "27017:27017"
    command: mongod --storageEngine=wiredTiger
    restart: always
  python:
    build: 
      context: ./notebook
    volumes: 
      - ./notebook/main:/tf
    environment: 
      - PASSWORD=password
    ports:
      - 8888:8888
    depends_on: 
    - db

