version: '3.7'
services:
  db:
    image: amirrezasalamat/rumi_mongo
    restart: always
  python:
    image: amirrezasalamat/social_interactions_python
    depends_on: db
  # go:
  #   image: amirrezasalamat/social_interactions_go
  #   depends_on: db


